baseURL = "https://example.com/"
languageCode = "en-us"
title = "A Hugo theme for creating Reveal.js presentations"
disableKinds = ["sitemap", "RSS"]

[author]
name = "Josh Dzielak"

[params]
description = "A description of this presentation"

[params.reveal_hugo]
theme = "solarized"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
