baseURL = "https://example.com/"
languageCode = "en-us"
title = "A Hugo theme for creating Reveal.js presentations"
disableKinds = ["sitemap", "RSS"]
theme = "."
themesDir = "../"

# uncomment for browsing at file:///
# relativeURLs = true
# uglyURLs = true

[author]
name = "Josh Dzielak"

# as of hugo 0.60 goldmark is the default
# reveal-hugo doesn't support goldmark yet
# so force to black friday
[markup]
# defaultMarkdownHandler = "blackfriday"
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
# setting the theme for highlighting by Hugo 
# we need a style that looks good in both light and dark background!
style = "tango"
# to allow the use of Highlight.js line numbers and highlights
# (see https://github.com/hakimel/reveal.js#line-numbers--highlights)
codeFences = false

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
history = true
# setting the theme for highlighting by Highlight.js
highlight_theme = "github"

# used in content/template-example
[params.reveal_hugo.templates.grey]
background = "#424242"
transition = "convex"