baseURL = "https://reveal-hugo.netlify.com/"
languageCode = "en-us"
title = "A Hugo theme for creating Reveal.js presentations"

[author]
name = "Josh Dzielak"

[params]
description = "A description of this presentation"
reveal_theme = "solarized"
